version: '2.0'

services:
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./wp-content:/var/www/html/wp-content
     ports:
       - "8009:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: my_wordpress_db_password
       WORDPRESS_DEBUG: 1

   db:
     image: mysql:5.7
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: my_db_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: my_wordpress_db_password       
   phpmyadmin:
       depends_on:
         - db
       image: phpmyadmin/phpmyadmin
       restart: always
       ports:
         - '8083:80'
       environment:
         PMA_HOST: db
         MYSQL_ROOT_PASSWORD: my_db_root_password
volumes:
    wp-content:
    db_data:


